services: 
  strava-service:
    build: ./strava_service
    ports: 
      - 8080:8080
  peer-server-service:
    build: ./peer_service
    ports: 
      - 9000:9000
  crash-logging-service:
    build: ./crash_logging_service
    ports:
      - 3000:3000
